### PR TITLE
paloaltocortexxdr: Bugfix - Update paloaltocortexxdr_connector.py

### PR DESCRIPTION
**Pull request by johnwhirsch**
Updated the "block hash" and "allow hash" API endpoints to match the documentation here: https://cortex-panw.stoplight.io/docs/cortex-xdr/82fd7689e4130-block-list-files

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

### CODE REVIEW

**Comment by mishalp-crest** [comment]
Hi @johnwhirsch  ,
As per our current standards, the min_phantom_version is required to be "5.5.0". Can you please test the app on that Splunk soar version?

**Review by achandya-crest — APPROVED** [review]

**Comment by mishalp-crest** [comment]
Hi @johnwhirsch ,
As per our current standards, the min_phantom_version is now updated and is required to be "6.0.0". Can you please test the app on that Splunk soar version and update it in the json file?

**Review by ighelani-crest — APPROVED** [review]

**Review by ighelani-crest — APPROVED** [review]

**Review by ighelani-crest — APPROVED** [review]

**Review by ighelani-crest — APPROVED** [review]

**Comment by mishalp-crest** [comment]
Keeping the minimum phantom version as 5.4.0 as there are no updates regarding the app's compatibility on 5.5.0 and 6.6.0. The pipeline is failing as the minimum phantom version is less than 5.5.0 only.

**Comment by ishans-crest** [comment]
The sanity test is failing because of min_phantom_version. As an exception, merging the PR.

**Pull request merged**
