### PR TITLE
paloaltocortexxdr: Feature - Isolated/unisolated improvement

### PR DESCRIPTION
**Pull request by EverdredIIDX**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [*] Testing of all the changes has been performed (for bug fixes / features)
- [*] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [*] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [*] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [*] Verify all checks are passing.
- [*] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [*] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [*] Bugfix
- [*] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
Current behavior of the scan endpoint action provides no way outside of the "scan all" option to filter by both isolated _and_ unisolated hosts. Furthermore, in the case of a playbook error and the intended IP filter is unintentionally passed in as an empty list, the scan endpoint action will scan all unisolated hosts. This isn't desirable behavior.

This change still allows users to filter by isolated/unisolated hosts, but if unspecified by the user won't add an isolated/unisolated filter at all. Additionally the "isolate" parameter is renamed to "isolated" in order to make it more clear that this is a filter, rather than a request to isolate the specified host. 

## What is the current behavior? (OPTIONAL)
User can either scan isolated hosts, or user can scan unisolated hosts.

## What is the new behavior? (OPTIONAL)
User can scan isolated hosts, unisolated hosts, or a combination of both.

---
Thanks for contributing!

### CODE REVIEW

**Comment by EverdredIIDX** [comment]
Tried to fix some of the minor lint failures, but I didn't want to take too many liberties considering this is just a small change.

**Comment by pdesai-crest** [comment]
Hello @cschmidt0121, 
Static test failure states that the min_phantom_version is too low, 
could you please check the working of app on the phantom version 5.5.0 if you wish to update the min_phantom_version?, or we can keep the min_phantom_version as it is.

**Comment by pdesai-crest** [comment]
Hello @cschmidt0121, 
Any updates on https://github.com/splunk-soar-connectors/paloaltocortexxdr/pull/3#issuecomment-1504775503

**Comment by EverdredIIDX** [comment]
> Hello @cschmidt0121, Any updates on [#3 (comment)](https://github.com/splunk-soar-connectors/paloaltocortexxdr/pull/3#issuecomment-1504775503)

Sorry about that. I've tested on version 5.4.0 as that's the version we are currently running. Is that still too low as a minimum version?

**Comment by pdesai-crest** [comment]
Hello @nastorSplunk,
Based on the best practices followed by us, we keep min_phantom_version 5.5.0.
Based on the comment by contributor https://github.com/splunk-soar-connectors/paloaltocortexxdr/pull/3#issuecomment-1511646051, he tested the app on 5.4.0.

What will you suggest?
Should we release the app with 5.4.0 min_phantom_version?

**Review by dhwanis-crest — APPROVED** [review]

**Review by mmomin-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
